enum APP_MODALS {
	LOGIN_MODAL = 'L0GIN_M0D4L',
	LOGIN_MODAL_DISCOVER_BUTTON = 'L0GIN_M0D4L_DISCOVER_BUTTON',
	CHART_MODAL = 'CH4RT_M0D4L',

	DEPLOYMENT_IN_PROGRESS_MODAL = 'D3PL0YM3N7_IN_PR0GR355',
	DEPLOYMENT_SUCCESS_MODAL = 'D3PL0YM3N7_55UCC3S',
}

export default APP_MODALS;
