// enum ERROR_CODES {
// 	EXAMPLE_ERROR = '3X4MPL3_3RR0R',
// }

// export default ERROR_CODES;

enum ERROR_CODES {
	// image upload
	IMAGE_SIZE_TOO_LARGE = 'IMAGE_SIZE_TOO_LARGE',
	IMAGE_INVALID_TYPE = 'IMAGE_INVALID_TYPE',
	IMAGE_INVALID_DIMENSIONS = 'IMAGE_INVALID_DIMENSIONS',

	IMAGE_PRESIGNED_URL_ERROR = 'IMAGE_PRESIGNED_URL_ERROR',
	UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR',

	// file
	FILE_SIZE_TOO_LARGE = 'FILE_SIZE_TOO_LARGE',

	//pwr

	PWR_PROVIDER_NOT_DETECTED = 1000,
}

export default ERROR_CODES;
